Script started on 2023-02-16 13:16:13-08:00
]0;jmau@WWWSTU-P01:~/hw1[jmau@WWWSTU-P01 hw1]$ gcc initials.c -ansi -Wall -o initials[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kexit./pipe[2Pexit[Kexit./pipegcc -Wall -ansi pipe.c -o pipe[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cemacs[Kgcc -Wall -ansi pipe.c -o pipe[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C./pipe[K[K[K[K[Kinitials
 J      J
J       J
 JJJJJJJJ
        J
        J
         
 CCCCCCC 
C       C
 C     C 
         
MMMMMMMMM
      MM 
    MM  
  MM   
    MM
      MM 
MMMMMMMMM
]0;jmau@WWWSTU-P01:~/hw1[jmau@WWWSTU-P01 hw1]$ exit
exit

Script done on 2023-02-16 13:16:52-08:00
