Script started on 2023-03-02 23:56:49-08:00
]0;jmau@WWWSTU-P01:~/hw3[jmau@WWWSTU-P01 hw3]$ exit./creditcardgcc creditcard.c -ansi -Wall -o creditcard[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexit[K./creditcard[6Pscript[4Plsemacs./blackjackgcc blackjack.c -ansi -Wall -o blackjack
]0;jmau@WWWSTU-P01:~/hw3[jmau@WWWSTU-P01 hw3]$ gcc blackjack.c -ansi -Wall -o blackjack[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexit[K./creditcardgcc creditcard.c -ansi -Wall -o creditcard[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexit[K./creditcard[6Pscript[4Plsemacs./blackjack
*********************************
**Welcome to CENG 231 BlackJack**
*********************************
Your first card is : 11
Do you want another card?
Type 1 for Yes, 0 for No:
1
Your next card is : 9
value : 9
value : 19
Your combined value is:19
Do you want another card?
Type 1 for Yes, 0 for No:
0
Dealer draws another card.
Dealer's card is: 6
Dealer's value is 6, you have 19
Dealer draws another card.
Dealer's card is: 3
Dealer's value is 9, you have 19
Dealer draws another card.
Dealer's card is: 4
Dealer's value is 13, you have 19
Dealer draws another card.
Dealer's card is: 7
Dealer's value is 20, you have 19
Sorry. You lose!
]0;jmau@WWWSTU-P01:~/hw3[jmau@WWWSTU-P01 hw3]$ exit
exit

Script done on 2023-03-02 23:57:26-08:00
